name_to_codename = {
    u'Chacarita': u'CHACARITA',
    u'Villa Crespo': u'VILLA CRESPO',
    u'Belgrano': u'BELGRANO',
    u'Recoleta': u'RECOLETA',
    u'Retiro': u'RETIRO',
    u'Villa Santa Rita': u'VILLA SANTA RITA',
    u'Barracas': u'BARRACAS',
    u'Palermo': u'PALERMO',
    u'Puerto Madero': u'PUERTO MADERO',
    u'Boca': u'BOCA',
    u'Parque Chas': u'PARQUE CHAS',
    u'Colegiales': u'COLEGIALES',
    u'Coghlan': u'COGHLAN',
    u'Villa Pueyrredon': u'VILLA PUEYRREDON',
    u'San Nicol\xe1s': u'SAN NICOLAS',
    u'Villa Real': u'VILLA REAL',
    u'Paternal': u'PATERNAL',
    u'San Telmo': u'SAN TELMO',
    u'Villa del Parque': u'VILLA DEL PARQUE',
    u'Villa Ort\xfazar': u'VILLA ORTUZAR',
    u'Almagro': u'ALMAGRO',
    u'Floresta': u'FLORESTA',
    u'Dique 3': u'Dique 3',
    u'Caballito': u'CABALLITO',
    u'Monte Castro': u'MONTE CASTRO',
    u'Flores': u'FLORES',
    u'Constituci\xf3n': u'CONSTITUCION',
    u'San Crist\xf3bal': u'SAN CRISTOBAL',
    u'Boedo': u'BOEDO',
    u'V\xe9lez Sarsfield': u'VELEZ SARSFIELD',
    u'Villa Luro': u'VILLA LURO',
    u'Parque Patricios': u'PARQUE PATRICIOS',
    u'Balvanera': u'BALVANERA',
    u'Mataderos': u'MATADEROS',
    u'Villa Lugano': u'VILLA LUGANO',
    u'Saavedra': u'SAAVEDRA',
    u'Escollera Exterior': u'ESCOLLERA EXTERIOR',
    u'Villa Urquiza': u'VILLA URQUIZA',
    u'Villa Gral. Mitre': u'VILLA GRAL. MITRE',
    u'Agronom\xeda': u'AGRONOMIA',
    u'Dique 4': u'Dique 4',
    u'Dique 1': u'Dique 1',
    u'Parque Avellaneda': u'PARQUE AVELLANEDA',
    u'Parque Chacabuco': u'PARQUE CHACABUCO',
    u'Dique 2': u'Dique 2',
    u'Nueva Pompeya': u'NUEVA POMPEYA',
    u'Villa Riachuelo': u'VILLA RIACHUELO',
    u'Villa Soldati': u'VILLA SOLDATI',
    u'Villa Devoto': u'VILLA DEVOTO',
    u'Liniers': u'LINIERS',
    u'Versalles': u'VERSALLES',
    u'Monserrat': u'MONSERRAT',
    u'Nu\xf1ez': u'NU\xd1EZ'}



codename_to_name = {
    u'BELGRANO': u'Belgrano',
    u'VILLA LURO': u'Villa Luro',
    u'PALERMO': u'Palermo',
    u'VILLA GRAL. MITRE': u'Villa Gral. Mitre',
    u'VILLA ORTUZAR': u'Villa Ort\xfazar',
    u'BOCA': u'Boca',
    u'CABALLITO': u'Caballito',
    u'BOEDO': u'Boedo',
    u'NUEVA POMPEYA': u'Nueva Pompeya',
    u'VILLA CRESPO': u'Villa Crespo',
    u'SAN CRISTOBAL': u'San Crist\xf3bal',
    u'Dique 1': u'Dique 1',
    u'BALVANERA': u'Balvanera',
    u'AGRONOMIA': u'Agronom\xeda',
    u'SAN TELMO': u'San Telmo',
    u'VILLA DEL PARQUE': u'Villa del Parque',
    u'COGHLAN': u'Coghlan',
    u'MONSERRAT': u'Monserrat',
    u'VILLA SANTA RITA': u'Villa Santa Rita',
    u'ALMAGRO': u'Almagro',
    u'BARRACAS': u'Barracas',
    u'MATADEROS': u'Mataderos',
    u'SAAVEDRA': u'Saavedra',
    u'VILLA URQUIZA': u'Villa Urquiza',
    u'VILLA SOLDATI': u'Villa Soldati',
    u'VILLA RIACHUELO': u'Villa Riachuelo',
    u'RETIRO': u'Retiro',
    u'CONSTITUCION': u'Constituci\xf3n',
    u'MONTE CASTRO': u'Monte Castro',
    u'VILLA DEVOTO': u'Villa Devoto',
    u'FLORESTA': u'Floresta',
    u'RECOLETA': u'Recoleta',
    u'PARQUE CHACABUCO': u'Parque Chacabuco',
    u'VILLA PUEYRREDON': u'Villa Pueyrredon',
    u'FLORES': u'Flores',
    u'VILLA REAL': u'Villa Real',
    u'NU\xd1EZ': u'Nu\xf1ez',
    u'Dique 3': u'Dique 3',
    u'SAN NICOLAS': u'San Nicol\xe1s',
    u'ESCOLLERA EXTERIOR': u'Escollera Exterior',
    u'COLEGIALES': u'Colegiales',
    u'VILLA LUGANO': u'Villa Lugano',
    u'PARQUE AVELLANEDA': u'Parque Avellaneda',
    u'CHACARITA': u'Chacarita',
    u'VERSALLES': u'Versalles',
    u'PATERNAL': u'Paternal',
    u'PARQUE CHAS': u'Parque Chas',
    u'LINIERS': u'Liniers',
    u'PUERTO MADERO': u'Puerto Madero',
    u'Dique 4': u'Dique 4',
    u'VELEZ SARSFIELD': u'V\xe9lez Sarsfield',
    u'Dique 2': u'Dique 2',
    u'PARQUE PATRICIOS': u'Parque Patricios'}
